# 基础镜像 jdk1.8
FROM openjdk:8

# 作者
MAINTAINER zhangyang

# 把可执行 jar 包复制到基础镜像的根目录下
ADD target/GithubActionDemo-0.0.1-SNAPSHOT.jar /GithubActionDemo-0.0.1-SNAPSHOT.jar

# 镜像要暴露的端口，如要使用端口，在执行 docker run 命令时使用 -p 生效
EXPOSE 8989

# 在镜像运行为容器后执行的命令
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/GithubActionDemo-0.0.1-SNAPSHOT.jar"]