# docker-image.yml
name: Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow

on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'main'
    tags:       # tag更新时触发此workflow  表示所有的tag
      - '*'

jobs:  # workflow中的job

  push_to_registry:  # job的名字
    name: Docker image to Docker Hub
    runs-on: ubuntu-latest   # job运行的基础环境
    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v2   # 官方的action，获取代码

      - name: Set up JDK  # 设置JDK
        uses: actions/setup-java@master  # 使用GitHub官方的setup-java action，用于安装和配置Java环境
        with:
          java-version: 17
          distribution: "adopt"
          cache: maven
          # 编译打包
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v1  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3  # 抽取项目信息，主要是镜像的tag
        with:
          images: ZhangYang19980825/GithubActionDemo


      - name: Build and push Docker image
        uses: docker/build-push-action@v4 # docker build & push
        with:
          context: .
          file: ./DockerFile
          push: true
          tags: zhangyang19980825/actions_build_springboot